# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: noahcabral.AeroForge
PackageVersion: 0.16.3
PackageLocale: en-US
Publisher: noahcabral
PublisherUrl: https://github.com/noahcabral
PublisherSupportUrl: https://github.com/noahcabral/aeroforge-nitrosense-alternative/issues
Author: noahcabral
PackageName: AeroForge Control
PackageUrl: https://github.com/noahcabral/aeroforge-nitrosense-alternative
License: MIT License
ShortDescription: Open-source NitroSense alternative for Windows 10/11
Tags:
- acer
- Nitro
- Fan
- Smart charging
ReleaseNotes: 'Changes:'
ReleaseNotesUrl: https://github.com/noahcabral/aeroforge-nitrosense-alternative/releases/tag/v0.16.3
Documentations:
- DocumentLabel: Wiki
  DocumentUrl: https://github.com/noahcabral/aeroforge-nitrosense-alternative/wiki
ManifestType: defaultLocale
ManifestVersion: 1.12.0
