# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: Throneproj.Throne
PackageVersion: 1.3.1
PackageLocale: en-US
Publisher: Throneproj
PublisherUrl: https://github.com/throneproj
PublisherSupportUrl: https://github.com/throneproj/Throne/issues
PackageName: Throne
PackageUrl: https://github.com/throneproj/Throne
License: GPL-3.0
LicenseUrl: https://github.com/throneproj/Throne/blob/HEAD/LICENSE
ShortDescription: Cross-platform GUI proxy utility (Empowered by sing-box)
Tags:
- Nekoray
- Proxy
- Throne
- sing-box
ReleaseNotesUrl: https://github.com/throneproj/Throne/releases/tag/1.3.1
ReleaseNotes: |
  Throne's Android client has had major rewrites to make it more compatible with the Desktop app in both logic and feature, please try the v2.0.0 release and file an issue for the problems you encounter

  - Fix Testing on Linux failing when Tun is on
  - Fix DNS not being hijacked in Tun mode
  - Fix Xray not inheriting interface bind
  - Fix Warp UDP socket binding
  - Fix Amnezia on MacOS
  - Fix legacy MacOS build
  - Add IPv6 defaults to private range bypass
  - Deprecate Hijack feature 1
  - Add customization features to Subscription Groups 2
  - Fixes and Improvements

  1:
  Hijack and Redirect features, alongside windows System DNS feature are deprecated and will be removed in the next release.

  2:
  Groups can now have custom UA/HWID, and perform testing/filtering automatically after update.
ManifestType: defaultLocale
ManifestVersion: 1.12.0
